### PR TITLE
Changed the title

### PR DESCRIPTION
**Pull request by alekssaul**

### CODE REVIEW

**Comment by botofalekssaul** [comment]
Success: Quay.io Built the image for you. See: https://quay.io/repository/aleks_saul/simplewebapp/build/494fa807-9c39-494e-9500-423a092ad40d . Your application is available at 104.196.138.84:80 or http://104.196.138.84:80

**Comment by likestocomment** [comment]
How about adding a tectonic logo?

**Comment by botofalekssaul** [comment]
Success: Quay.io Built the image for you. See: https://quay.io/repository/aleks_saul/simplewebapp/build/2decc857-010d-4510-bff4-cf1a7f0b8ff7 . Your application is available at 104.196.140.37:80 or http://104.196.140.37:80

**Comment by botofalekssaul** [comment]
Looks like the Pull Request is closed, all Kubernetes objects associated to this PR has been removed

**Pull request closed without merging**
