### PR TITLE
change the frontpage

### PR DESCRIPTION
**Pull request by alekssaul**
Need this in the master, maybe

### CODE REVIEW

**Comment by botofalekssaul** [comment]
Success: Quay.io Built the image for you. See: https://quay.io/repository/aleks_saul/simplewebapp/build/9de3fcc0-1371-48ee-a782-67079bb6e88c . Your application is available at ad371fc663cb511e7973f06b08a62f05-1079804189.us-west-1.elb.amazonaws.com:80 or http://ad371fc663cb511e7973f06b08a62f05-1079804189.us-west-1.elb.amazonaws.com:80

**Comment by likestocomment** [comment]
That picture is ugly, you should replace it.

**Comment by botofalekssaul** [comment]
Success: Quay.io Built the image for you. See: https://quay.io/repository/aleks_saul/simplewebapp/build/0a5935fa-6f62-42fb-b658-bd6c412bd466 . Your application is available at a681d9e763cb611e7973f06b08a62f05-1407669581.us-west-1.elb.amazonaws.com:80 or http://a681d9e763cb611e7973f06b08a62f05-1407669581.us-west-1.elb.amazonaws.com:80

**Comment by botofalekssaul** [comment]
Looks like the Pull Request is closed, all Kubernetes objects associated to this PR has been removed

**Pull request closed without merging**
